language: objective-c

before_install:
 - brew update
 - brew upgrade xctool # xctool 0.1.13(Installed in Travis-CI) can't run Specta test
 - gem install cocoapods -r
 - pod setup

script: xctool build test
